spring.application.name=Customer-Api

#spring.datasource.url=jdbc:mysql://localhost:3306/ecom
#spring.datasource.username=root
#spring.datasource.password=root
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update

#server.port=9091

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=sainithinjava@gmail.com
#spring.mail.password=uuvg traz qldc osta
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.config.import=optional:configserver:http://localhost:8081
management.endpoints.web.exposure.include=refresh